# Editor's Choice products for AltaCoco Home. Specs verified on crateandbarrel.com on the date in CHECKED.
# Editorial text is our own; nothing here claims firsthand testing.

CHECKED = "September 16, 2026"

PRODUCTS = [
dict(slug="gather-deep-sectional-family-living", tag="Best for Family Lounging",
     title="A Deep Sectional That Actually Works for Family Living",
     summary="Generous enough for everyday lounging without looking overly bulky.",
     cats=["Sofas & Sectionals", "Family-Friendly Picks"], img="ec-sectional.jpg", tone="sand", mark="sofa",
     brand="Crate & Barrel", product="Gather Deep 2-Piece Sectional Sofa with Chaise Lounge", category="Sofa / Sectional",
     price="$3,598 as configured (Icon fabric in Stone, track arm)", dims='120"W × 68"D × 36"H (sofa + chaise)',
     seat='Seat height 19"; deep 43" option; chaise seat depth 53"', material="FSC-certified engineered hardwood frame; innerspring seat cushions wrapped in polyfoam and fiber; fiber back cushions; sinuous spring suspension; made in USA",
     best_for="Family rooms, larger living rooms, relaxed seating", url="https://www.crateandbarrel.com/gather-deep-2-piece-sectional-sofa-with-chaise-lounge/s253595", reviews="2,100+",
     why=["Gather is Crate & Barrel's clean-lined, Scandinavian-leaning sectional, and the Deep version is the one to look at if your evenings involve lying down more than sitting up. The boxy cushions and slim 4-inch track arm keep the silhouette simple, so the sofa reads as modern rather than overstuffed even at 43 inches deep.",
          "The construction is the reason it made this list over similar-looking sectionals: an FSC-certified hardwood frame, innerspring seat cushions rather than plain foam, and a sinuous-spring deck. Those are the parts that determine whether a sofa still sits well in year five.",
          "It is also unusually configurable. Left- or right-arm chaise, an apartment-width version, an extra-wide chaise, five arm styles, and a wide fabric library, so it can be tuned to the room instead of the other way round."],
     notes=["Best in rooms with enough circulation around a 68-inch overall depth; keep 30 to 36 inches clear in front of the chaise.",
            "Works especially well with a large low-pile rug (9 by 12) and a coffee table no taller than the 19-inch seat.",
            "A mid-tone performance fabric hides more than the pale Stone shown; order swatches, they are free.",
            "The diagonal depth is 68 inches; check doorways and stair turns before ordering."],
     consider=["The 43-inch depth is real lounging depth. If you sit upright to read or work, the standard-depth Gather (same design, shallower seat) will suit you better.",
               "Fiber-filled back cushions are soft and need occasional fluffing; if you prefer a crisp, tailored back, look at the tight-back options in the same family."],
     why_ec="Comfort + clean Scandinavian lines + hardwood and innerspring construction + configurable to the room",
     pairing=["A low oak or walnut coffee table", "A textured wool rug in oatmeal or grey", "One sculptural floor lamp behind the chaise", "A contrasting lounge chair in wood and linen", "Warm wood side tables"]),

dict(slug="hearth-round-extendable-dining-table", tag="Best Small-Space Dining Pick",
     title="A Dining Table That Seats More Than It Looks",
     summary="A compact footprint, useful proportions, and a shape that works especially well in tighter rooms.",
     cats=["Dining Tables", "Small-Space Picks"], img="ec-dining-table.jpg", tone="oat", mark="table",
     brand="Crate & Barrel", product='Hearth 49"–71" Oak Round Extendable Dining Table', category="Dining Table",
     price="$1,999", dims='48.5" diameter × 30"H round; extends to 70.5" × 48.5" oval with the included leaf',
     seat="Seats 4, extends to seat 6", material="FSC-certified oak, oak veneer and engineered wood; wire-brushed warm brown finish; kiln-dried; adjustable levelers; made in Indonesia",
     best_for="Dining rooms and eat-in kitchens under about 11 by 12 feet, apartments, households that host occasionally", url="https://www.crateandbarrel.com/hearth-49-71-oak-round-extendable-dining-table/s476431", reviews="new",
     why=["A 48-inch round is the most forgiving dining shape for a small room: no corners to walk around, everyone can see everyone, and it takes up noticeably less visual space than a rectangle of the same seating. Hearth adds the trick that makes it practical, a stored leaf that turns it into a 70-inch oval for six.",
          "The design is quiet in the right way. A thick, arc-edged top and rounded plank legs give it presence without ornament, and the legs are angled outward so knees clear them, which matters on a round table more than people expect.",
          "Oak with a wire-brushed finish shows grain and hides the small marks a dining table collects."],
     notes=["Allow 36 inches of clearance around the round footprint, 42 on the side people pass through.",
            "With the leaf in, the oval needs roughly 11 feet of room length to seat six comfortably.",
            "Pairs well with armless chairs; check that chair arms clear the recessed apron if you prefer armchairs.",
            "A 6-by-9 rug fits under the round; go to 8-by-10 if you extend it often."],
     consider=["The top is oak veneer over engineered wood rather than solid planks, which keeps it stable and affordable but limits deep refinishing. It is a good table for fifteen years, not necessarily for fifty.",
               "This is a newer design with few reviews at the time of checking, so long-term reports are thin."],
     why_ec="Round-to-oval flexibility + honest proportions + a finish that wears well + fair price",
     pairing=["Four light spindle or bentwood chairs", "One pendant centered over the table, bottom 30 to 36 inches above the top", "A low ceramic bowl rather than a tall centerpiece", "A round or oval rug sized to the extended table"]),

dict(slug="corfu-ceramic-pendant", tag="Best Statement Light",
     title="A Pendant That Can Carry the Room",
     summary="Simple enough to live with long term, distinctive enough to become the focal point.",
     cats=["Lighting", "Splurge-Worthy Pieces"], img="ec-pendant.jpg", tone="stone", mark="lamp",
     brand="Crate & Barrel", product='Corfu Large Cream Ceramic Pendant Light 18"', category="Pendant Light",
     price="$399", dims='18" diameter × 15" shade height; hangs from 16.25" to 87"', seat="—",
     material="Clay shade with matte cream finish; burnished-brass metal hardware and 6-inch ceiling plate; adjustable chain and fabric-wrapped cord; one E26 socket, up to 100W incandescent or 9W LED; dimmer compatible; hardwired",
     best_for="Over a dining table, a kitchen island end, or an entry", url="https://www.crateandbarrel.com/corfu-large-cream-ceramic-pendant-light-18/s181955", reviews="26",
     why=["Most statement pendants shout. Corfu does the opposite: a single tapered ceramic shade in matte cream, 18 inches across, with a soft curve and a slightly rustic surface. It reads as an object rather than a fixture, which is what makes it able to anchor a room without dating it.",
          "Ceramic is the right material for this job. It has weight and texture that painted metal does not, and it throws a warm, downward pool of light that suits a dining table.",
          "At under $400 it is inexpensive for a fixture that does this much work, and the brass hardware ties it to the lamps and pulls most people already own."],
     notes=["Sized for a table 42 to 60 inches wide; over a longer table, use two or step up to a linear fixture.",
            "Hang the bottom of the shade 30 to 36 inches above the tabletop.",
            "Use a warm (2700K) LED and a dimmer; the fixture is dimmer compatible.",
            "Suitable for slanted ceilings; not for bathrooms."],
     consider=["The shade is opaque, so light goes down, not out. In a dining room lit only by this pendant, add a lamp or sconce elsewhere for ambient fill.",
               "Ceramic is heavy for its size; confirm the junction box is rated for the fixture weight and have it professionally installed."],
     why_ec="Sculptural without being trendy + warm ceramic light + brass details + strong value",
     pairing=["A wood dining table in oak or walnut", "Linen or paper table lamps elsewhere in the room, so the finishes relate", "A rattan or woven element nearby to echo the handmade texture"]),

dict(slug="ojai-wood-accent-chair", tag="Best Value",
     title="A Well-Proportioned Lounge Chair Under $1,000",
     summary="A strong silhouette and practical dimensions at a price point that leaves room in the budget for the rest of the room.",
     cats=["Chairs", "Best Value"], img="ec-lounge-chair.jpg", tone="clay", mark="chair",
     brand="Crate & Barrel", product="Ojai Wood Accent Chair", category="Lounge / Accent Chair",
     price="$999 (Bliss fabric in Cloud; stocked)", dims='33"W × 36"D × 29.5"H', seat='Seat 24"W × 23"D × 16.5"H; arm height 22.75"',
     material="FSC-certified hardwood and oak frame with mortise-and-tenon joinery; sinuous coil suspension; high-resiliency foam and polyfiber; poly-linen fabric; imported",
     best_for="Living room corners, beside a sofa, bedrooms, reading spots", url="https://www.crateandbarrel.com/ojai-wood-accent-chair/s411188", reviews="200+",
     why=["Ojai borrows from Shaker and Danish Modern at once: an exposed oak frame with proper mortise-and-tenon joints, softly rounded edges, shaped armrests, and tight seat and back cushions angled for a relaxed sit. It is the kind of chair that looks right in a warm-minimal room and still looks right after the sofa changes.",
          "The dimensions are the reason it earns the value label. At 33 inches wide and 36 deep it has real lounge-chair presence, but the open wood frame keeps it visually light, so it works in a room where a fully upholstered chair would feel heavy.",
          "The $999 price is for the stocked fabric; the chair is a Crate & Barrel exclusive with a solid review history."],
     notes=["Reads best in pairs flanking a fireplace or window, or as a single contrast chair beside a linen sofa.",
            "The 16.5-inch seat height is on the low, relaxed side; pair with a side table around 20 inches.",
            "The exposed frame benefits from a rug underneath so the legs do not look stranded on a bare floor."],
     consider=["Tight (non-removable) cushions mean spills are spot-cleaned, not laundered; choose a mid-tone fabric for a family room.",
               "This is a lounge chair, not a deep armchair. If you want to curl up sideways, look at something wider and softer."],
     why_ec="Danish-Shaker proportions + visible joinery + open, light footprint + under $1,000",
     pairing=["A small round oak side table", "A linen or wool throw over the arm", "A floor lamp with a linen shade behind one shoulder", "A second Ojai for a conversation pair"]),

dict(slug="prato-performance-wool-rug", tag="Rugs",
     title="A Wool Rug Sized for Real Living Rooms",
     summary="Available in the larger sizes most living rooms actually need, with a low pile that suits high-traffic spaces.",
     cats=["Rugs", "Family-Friendly Picks"], img="ec-wool-rug.jpg", tone="sage", mark="rug",
     brand="Crate & Barrel", product="Prato Performance Wool Oatmeal Beige Area Rug", category="Area Rug",
     price="$1,499 for 8'×10' (also 6'×9', 9'×12', 10'×14', 12'×15')", dims="8'×10' shown; sizes up to 12'×15'", seat="—",
     material="Handwoven 55% wool, 25% polyester, 20% viscose pile on a cotton foundation; serged edges; GoodWeave certified; made in India",
     best_for="Living rooms, family rooms, entries, other high-traffic spaces", url="https://www.crateandbarrel.com/prato-performance-wool-oatmeal-beige-area-rug-8x10/s190075", reviews="43",
     why=["The rug most people need is large, neutral, low-pile, and tough. Prato is exactly that: undyed wool woven into nubby stripes, in oatmeal with tan and grey variation that hides everyday marks, and offered in the 9-by-12 and 10-by-14 sizes that most living rooms are actually sized for.",
          "The blend is deliberate. Wool gives it the hand and resilience; the polyester binds the yarns and cuts shedding; a little viscose adds sheen. The result is a rug that looks like a plain wool flatweave but behaves better underfoot and under a vacuum.",
          "GoodWeave certification is a meaningful mark on a handwoven rug."],
     notes=["Choose the size that puts all front legs of the seating on the rug: 8-by-10 for a standard sofa and two chairs, 9-by-12 for a sectional.",
            "Use a rug pad; the low pile shows slipping and bunching more than a thick rug does.",
            "Order the free swatch. The oatmeal reads warmer or cooler depending on the floor."],
     consider=["A 20 percent viscose share means it is not the right rug for a room where liquids hit the floor often; viscose marks with water. For a playroom, look at an all-wool or indoor-outdoor option.",
               "Handwoven wool rugs shed for the first few months; regular vacuuming without a beater bar settles it."],
     why_ec="Real living-room sizes + neutral texture that hides wear + wool hand with a practical blend + ethical certification",
     pairing=["A linen or performance-fabric sofa in a slightly darker neutral", "A wood coffee table so the rug is not the only warm element", "A second, smaller vintage or patterned rug layered on top if you want color"]),

dict(slug="bodie-oak-kids-storage-bed", tag="Kids",
     title="A Bed That Grows With the Room",
     summary="Simple lines and solid construction that will not look out of place as a child's room changes.",
     cats=["Kids", "Beds"], img="ec-kids-bed.jpg", tone="oat", mark="bed",
     brand="Crate & Kids (Crate & Barrel)", product="Bodie Natural Oak Wood Spindle Kids Storage Bed", category="Kids Bed",
     price="$1,599 (full; twin also available)", dims='Full: 56"W × 79"D × 40"H', seat="Fits a standard 7 to 12-inch mattress; no box spring needed",
     material="FSC-certified solid poplar, engineered wood and oak veneer; natural oak finish; GREENGUARD Gold certified; two built-in drawers on metal glides, mountable on either side; made in Vietnam",
     best_for="Kids from the first big-kid bed through the teenage years; smaller rooms that need storage", url="https://www.crateandbarrel.com/bodie-natural-oak-wood-spindle-kids-full-storage-bed/s473528", reviews="30",
     why=["The mistake with kids' beds is buying something childish that has to be replaced at ten. Bodie avoids it: a spindle headboard with a gentle curve, slightly angled back legs, and a natural oak finish. It is a classic bed scaled for a child's room, and it will read as a grown-up bed when the room grows up.",
          "The two drawers in the base are the practical reason to choose it over a plain frame. They are on metal glides, can be mounted on either side, and take the toys and bedding that otherwise live on the floor.",
          "GREENGUARD Gold certification matters more in a child's bedroom than anywhere else in the house."],
     notes=["The tall headboard (40 inches) gives enough back support for reading together; allow for it against a window sill.",
            "Choose the drawer side before delivery based on which side is open in the room.",
            "Natural oak pairs with almost any wall color; keep bedding simple and let the wood do the work."],
     consider=["Oak veneer over engineered wood on some panels means it should be treated like fine furniture, not scrubbed. It is durable, not indestructible.",
               "The full size is generous for a small room; the twin version has the same design in a smaller footprint."],
     why_ec="Classic proportions that age well + built-in storage + safety and air-quality certifications + solid construction",
     pairing=["A simple wood nightstand from the same collection or a small stool", "A washable low-pile rug", "A wall-mounted reading light rather than a table lamp", "White or natural linen bedding with one accent color"]),

dict(slug="petrie-midcentury-apartment-sofa", tag="Small-Space Picks",
     title="A Compact Sofa With Full-Size Comfort",
     summary="Apartment-scale dimensions without the shallow seat that usually comes with them.",
     cats=["Sofas & Sectionals", "Small-Space Picks"], img="ec-compact-sofa.jpg", tone="stone", mark="sofa",
     brand="Crate & Barrel", product='Petrie 76" Midcentury Apartment Sofa', category="Sofa",
     price="$1,999 (Jonas fabric in Felt Grey)", dims='76"W × 36"D × 32"H (34.5" with back cushions)', seat='Seat 69"W × 23"D × 19"H; arm height 25"; diagonal depth 34"',
     material="Kiln-dried hardwood benchmade frame; sinuous spring suspension; soy-based polyfoam seat cushions wrapped in fiber; fiber back cushions; hand button-tufted; ebony-stained hardwood legs; made in USA",
     best_for="Apartments, condos, studies, secondary living rooms, narrow rooms", url="https://www.crateandbarrel.com/petrie-76-midcentury-apartment-sofa/s148145", reviews="580+",
     why=["Most apartment sofas save space by shrinking the seat, which is the part you sit on. Petrie keeps a 23-inch seat depth and a 19-inch seat height, which is a proper full-size sit, and saves the space in the arms instead: slim 3.5-inch track arms on a 76-inch frame.",
          "It is a genuine 1960s silhouette, with boxy hand-tufted cushions and tapered ebony legs, and a Crate & Barrel classic with hundreds of reviews behind it. The menswear-style heathered fabric hides wear and reads as tailored rather than plush.",
          "The 34-inch diagonal depth is the number that matters for older buildings: this sofa fits through doors and up stairs that stop deeper sofas."],
     notes=["The upright sit suits reading and conversation; it is not a nap sofa.",
            "Legs show the floor beneath, which makes a small room feel larger; keep the rug low-pile so the line stays clean.",
            "Works well with a single lounge chair angled toward it rather than a matching loveseat."],
     consider=["Firm and upright by design. If you want to sink in, this is the wrong sofa; look at the Lounge apartment sofa in the same family.",
               "Button tufting collects crumbs in a house with small children."],
     why_ec="Full seat depth in a 76-inch frame + slim arms + fits through narrow doors + a proven design",
     pairing=["A round wood or marble coffee table", "A brass or black floor lamp", "One lounge chair in a contrasting wood frame", "A 6-by-9 or 8-by-10 flatweave rug"]),

dict(slug="lakin-white-oak-credenza", tag="Storage",
     title="A Sideboard With Useful Proportions",
     summary="Enough depth to be practical, low enough to sit comfortably under a window or artwork.",
     cats=["Storage", "Dining Tables"], img="ec-sideboard.jpg", tone="sand", mark="storage",
     brand="Crate & Barrel", product='Lakin 71" White Oak Wood Credenza', category="Credenza / Sideboard",
     price="$2,299", dims='71"W × 20"D × 33.5"H', seat="Three drawers (20.5\" × 16\" × 3\" inside) plus one single- and one double-door cabinet with three removable shelves",
     material="Solid white oak planks with satin natural finish; splayed aluminum legs with antiqued black finish; cord-management cutout; anti-tip hardware; levelers; made in India",
     best_for="Dining rooms, living room walls, entries, under a mounted television", url="https://www.crateandbarrel.com/lakin-71-white-oak-wood-credenza/s359347", reviews="230+",
     why=["Twenty inches deep and thirty-three and a half high is the sideboard sweet spot: deep enough for serving dishes and board games, low enough to sit under a window or beneath a large piece of art without crowding it. Lakin hits both numbers.",
          "The design is plank white oak with waterfall edges, flat doors, and no visible hardware, so the grain does the decorating. The splayed black aluminum legs give it a lift off the floor that keeps 71 inches of cabinet from feeling like a wall.",
          "Inside, it is more useful than most: three drawers, two cabinets with removable shelves, and a cord cutout, so it works as a media console as well as a dining sideboard."],
     notes=["Leave 4 to 6 inches of wall on each side; a sideboard that runs edge to edge looks built-in and loses the floating effect.",
            "Art above should span roughly two-thirds of the width; a single lamp at one end balances a bowl or stack of books at the other.",
            "The natural finish will amber slightly with light over time; that is oak doing what oak does."],
     consider=["Plank construction means visible variation in color and grain between boards. It is the point of the piece, but if you want a uniform slab look, this is not it.",
               "Twenty inches of depth holds serving pieces but not large platters standing upright."],
     why_ec="Correct proportions + real white oak + serious storage inside + a lifted, light stance",
     pairing=["A ceramic table lamp at one end", "A large piece of art or a round mirror above", "A low bowl or stack of books to balance the lamp", "A woven basket beneath for the overflow"]),

dict(slug="remi-linen-floor-lamp", tag="Lighting",
     title="A Floor Lamp for Reading Corners",
     summary="Quietly sculptural, warm in the evening, and easy to pair with a range of lounge chairs.",
     cats=["Lighting", "Best Value"], img="ec-floor-lamp.jpg", tone="clay", mark="lamp",
     brand="Crate & Barrel", product='Remi Natural Linen Floor Lamp 65"', category="Floor Lamp",
     price="$399", dims='65.4"H × 23" shade diameter; base 50.75"H × 13" diameter', seat="—",
     material="Steel with burnished-brass finish wrapped in ivory linen; ivory linen shade; two E26 sockets (60W incandescent or 9W LED each); two brass pull chains; 12-foot cord; imported",
     best_for="Beside a lounge chair or sofa end, bedroom corners, any room that needs a warm secondary light", url="https://www.crateandbarrel.com/remi-natural-linen-floor-lamp-65/s129037", reviews="12",
     why=["A reading corner needs light at shoulder height, a shade that glows rather than glares, and a lamp that looks like furniture rather than equipment. Remi manages all three: a columnar base wrapped entirely in slubbed ivory linen, a wide matching shade, and burnished brass accents at the joints.",
          "Two sockets on separate pull chains is the practical detail. One bulb for evening ambience, two for reading. With warm LEDs it draws almost nothing.",
          "At 65 inches with a 23-inch shade it has enough scale to hold its own next to a deep lounge chair or the end of a sectional."],
     notes=["Place it so the shade bottom sits just above eye level when seated; the 50-inch base height is right for most lounge chairs.",
            "Use 2700K bulbs; the linen shade warms them further.",
            "The 23-inch shade needs about 30 inches of floor space; measure the corner."],
     consider=["Linen wrap on the base is beautiful and not scrubbable; keep it away from a kids' craft table.",
               "This is soft, ambient light. For a true task lamp with a directed beam, pair it with a small adjustable reading light."],
     why_ec="Furniture-like presence + two-bulb flexibility + linen warmth + under $400",
     pairing=["An oak-frame lounge chair like the Ojai", "A small round side table for the book", "A wool throw", "A second Remi in a bedroom for consistency across rooms"]),

dict(slug="terra-solid-white-oak-dining-table", tag="Splurge-Worthy Pieces",
     title="A Solid-Wood Dining Table Built to Last",
     summary="A single investment piece that anchors the room and holds up to daily use for decades.",
     cats=["Dining Tables", "Splurge-Worthy Pieces"], img="ec-solid-wood-table.jpg", tone="sage", mark="table",
     brand="Crate & Barrel", product='Terra 90" Natural White Oak Solid Wood Dining Table', category="Dining Table",
     price="$2,499", dims='90"W × 37"D × 30"H; 1.5" thick top; 25.7" floor to apron; 80" between legs', seat="Seats 8",
     material="FSC-certified solid white oak, hand-sanded, joined and finished; natural oak finish with ivory ceruse; legs intersect the slab top showing end grain; made in Romania",
     best_for="Dining rooms with room for a 90-inch table, families who gather, anyone who wants a table to refinish rather than replace", url="https://www.crateandbarrel.com/terra-90-natural-white-oak-solid-wood-dining-table/s254817", reviews="300+",
     why=["This is what a solid-wood table should be: inch-and-a-half planks of white oak, hand-finished, with legs that pass through the top so the end grain shows on the surface. There is no apron to hide the joinery and nothing to peel or delaminate. In thirty years it can be sanded and oiled and look new.",
          "Ninety inches seats eight without anyone sharing a corner, and the 37-inch width is generous enough for serving dishes down the center.",
          "The ivory ceruse finish sits in the grain and keeps the oak pale and Scandinavian rather than orange, which is the finish most people are looking for right now and few solid tables offer."],
     notes=["Needs a room at least 13 feet long to allow 36-inch clearance at both ends.",
            "Solid oak moves with the seasons; a humidifier in a dry winter house keeps joints tight.",
            "Knots, checking, and color variation are expected and are the point.",
            "Bench on one side and chairs on the other keeps the heavy table from feeling heavier."],
     consider=["It weighs over 200 pounds and does not come apart; plan the delivery path.",
               "The natural finish is not a thick film; use trivets and wipe spills. It will develop a patina, which is either the appeal or the drawback depending on the household."],
     why_ec="Solid FSC white oak + honest joinery + refinishable for life + a pale finish that suits modern rooms",
     pairing=["Six to eight light-framed chairs in oak or black", "A linear pendant or two matching ceramic pendants", "A wool runner on the table rather than a full cloth", "A credenza in the same white oak"]),

dict(slug="mallorca-wood-outdoor-sofa", tag="Outdoor",
     title="An Outdoor Sofa That Does Not Look Like Outdoor Furniture",
     summary="Deep, comfortable seating in weatherproof materials that would not look out of place indoors.",
     cats=["Outdoor", "Family-Friendly Picks"], img="ec-outdoor-sofa.jpg", tone="sage", mark="sofa",
     brand="Crate & Barrel", product='Mallorca 85" Wood Outdoor Sofa with Ivory Cushions', category="Outdoor Sofa",
     price="$3,099 (ivory cushions; Sunbrella colors available)", dims='85.4"W × 37"D × 23.8"H frame', seat='Seat depth 35.6"; seat cushion 12" thick',
     material="FSC-certified eucalyptus wood, painted and heavy wire-brushed to a driftwood finish; water-repellent, fade-resistant acrylic cushion covers (Sunbrella optional); foam-core cushions wrapped in polyester with mesh ventilation panels; levelers; made in Indonesia",
     best_for="Covered patios, decks, terraces; households that want an outdoor living room rather than a set of chairs", url="https://www.crateandbarrel.com/mallorca-85-wood-outdoor-sofa-with-ivory-cushions/s575532", reviews="46",
     why=["Mallorca reads like a low, wide Scandinavian sofa that happens to live outside. A plinth base, wide flat arms, and a linear eucalyptus frame in a grey driftwood finish, with deep ivory cushions on top. Put it under a covered patio next to a low table and it is an outdoor living room.",
          "The cushion construction is what separates it from furniture that looks similar and fails in two summers: acrylic covers that shed water and resist fade, foam cores wrapped in polyester, and mesh panels underneath so the cushion dries from the inside.",
          "Eucalyptus is a dense hardwood that handles weather well for its price; wire-brushing it means small scuffs disappear into the texture."],
     notes=["A 35-inch seat depth is lounging depth; pair it with a low table no higher than the 12-inch cushion top.",
            "In the Pacific Northwest, stand cushions on edge after rain and store or cover them over winter.",
            "The wood will silver further with sun; a yearly wipe-down with wood cleaner keeps it even.",
            "Ivory shows dirt; the Sunbrella colorways cost more and hide more."],
     consider=["At 85 inches wide and 37 deep it is a full-size sofa; measure the patio and the path to it.",
               "Eucalyptus is not teak. It needs slightly more care and will not last as many decades."],
     why_ec="Indoor proportions outdoors + real weatherproof cushion construction + wire-brushed hardwood + modular family",
     pairing=["A concrete or teak low table", "Two matching lounge chairs from the same collection", "An outdoor rug in a flat weave", "Large planters at both ends to frame it"]),

dict(slug="alfresco-outdoor-cafe-set", tag="Outdoor",
     title="A Dining Set Sized for Balconies",
     summary="A compact table and easy chairs that turn a small balcony or side patio into a place to actually eat.",
     cats=["Outdoor", "Small-Space Picks", "Dining Tables"], img="ec-outdoor-dining.jpg", tone="oat", mark="table",
     brand="Crate & Barrel", product='Alfresco 35" Black Metal Outdoor Cafe Table Set with Silver Sunbrella Cushions', category="Outdoor Dining Set",
     price="$2,041 for the set (table + 4 chairs)", dims='Table 35.4" × 35.4" × 29.3"H', seat="Seats 4; use two chairs on a narrow balcony",
     material="Rustproof aluminum frames with weather-resistant faux-wood slats in black powdercoat; solution-dyed acrylic Sunbrella seat cushions with foam cores and mesh ventilation; umbrella opening; levelers; made in Cambodia",
     best_for="Balconies, small decks, side yards, a breakfast corner off the kitchen", url="https://www.crateandbarrel.com/alfresco-35-black-metal-outdoor-cafe-table-set-with-silver-sunbrella-cushions/s621836", reviews="620+",
     why=["A 35-inch square is the largest table that still works on a typical apartment balcony, and Alfresco makes that footprint feel like a real dining spot rather than a bistro afterthought. Black slatted aluminum, clean lines, and low-profile Sunbrella cushions that stay out when it drizzles.",
          "The materials are the practical case. Aluminum does not rust; the powdercoat holds up in sun; the faux-wood slats give the warmth of wood without the annual oiling. It is the set you can leave outside.",
          "With over six hundred reviews it is one of Crate & Barrel's most-owned outdoor pieces, which counts for something in a category full of new designs."],
     notes=["On a balcony under 6 feet deep, use two chairs and keep the other two inside for guests.",
            "The umbrella opening means a small market umbrella fits without a separate base on a sunny balcony.",
            "Black metal gets hot in full afternoon sun; the cushions are the point of the set."],
     consider=["Faux-wood slats are a good imitation, not real wood; if you want the real thing, the Mallorca collection is the step up.",
               "Do not leave glassware on the tabletop in strong sun; the slats can mark under magnified heat."],
     why_ec="Balcony-scale footprint + rustproof, leave-it-out materials + Sunbrella cushions + a long track record",
     pairing=["A small planter or two at the rail", "A string of warm outdoor lights overhead", "A washable outdoor runner under the table", "A compact side table for the drinks"]),
]
