#!/bin/bash
# 把这个文件放在 site/images/ 里运行（或在 site/images 目录下运行）。
# 从 Unsplash 官方下载接口下载每张图，宽度 2400px，自动用正确的文件名保存。
cd "$(dirname "$0")"

curl -L -sS "https://unsplash.com/photos/OtXADkUh3-I/download?force=true&w=2400" -o "lookbook-01-wide.jpg" && echo "ok  lookbook-01-wide.jpg" || echo "FAIL lookbook-01-wide.jpg"
curl -L -sS "https://unsplash.com/photos/UrQeWGobTnI/download?force=true&w=2400" -o "ec-sideboard.jpg" && echo "ok  ec-sideboard.jpg" || echo "FAIL ec-sideboard.jpg"
curl -L -sS "https://unsplash.com/photos/SRZcOAERBUQ/download?force=true&w=2400" -o "about-hero.jpg" && echo "ok  about-hero.jpg" || echo "FAIL about-hero.jpg"
curl -L -sS "https://unsplash.com/photos/7mmmEkyk0aQ/download?force=true&w=2400" -o "ec-lounge-chair.jpg" && echo "ok  ec-lounge-chair.jpg" || echo "FAIL ec-lounge-chair.jpg"
curl -L -sS "https://unsplash.com/photos/ulh3-dLSXjI/download?force=true&w=2400" -o "lookbook-01-detail-b.jpg" && echo "ok  lookbook-01-detail-b.jpg" || echo "FAIL lookbook-01-detail-b.jpg"
curl -L -sS "https://unsplash.com/photos/Gkig1kUYl4c/download?force=true&w=2400" -o "post-sectional-2.jpg" && echo "ok  post-sectional-2.jpg" || echo "FAIL post-sectional-2.jpg"
curl -L -sS "https://unsplash.com/photos/nQBc6clG3X4/download?force=true&w=2400" -o "ec-sectional.jpg" && echo "ok  ec-sectional.jpg" || echo "FAIL ec-sectional.jpg"
curl -L -sS "https://unsplash.com/photos/LKI3Dd146vI/download?force=true&w=2400" -o "lookbook-02-wide.jpg" && echo "ok  lookbook-02-wide.jpg" || echo "FAIL lookbook-02-wide.jpg"
curl -L -sS "https://unsplash.com/photos/P0q_HK_-GGM/download?force=true&w=2400" -o "post-sectional-1.jpg" && echo "ok  post-sectional-1.jpg" || echo "FAIL post-sectional-1.jpg"
curl -L -sS "https://unsplash.com/photos/RqO6kwm4tZY/download?force=true&w=2400" -o "post-sectional-3.jpg" && echo "ok  post-sectional-3.jpg" || echo "FAIL post-sectional-3.jpg"
curl -L -sS "https://unsplash.com/photos/cXmER3VNxUA/download?force=true&w=2400" -o "ec-dining-table.jpg" && echo "ok  ec-dining-table.jpg" || echo "FAIL ec-dining-table.jpg"
curl -L -sS "https://unsplash.com/photos/zGKRmwzplVc/download?force=true&w=2400" -o "lookbook-04-wide.jpg" && echo "ok  lookbook-04-wide.jpg" || echo "FAIL lookbook-04-wide.jpg"
curl -L -sS "https://unsplash.com/photos/yJ97mWnHTVE/download?force=true&w=2400" -o "ec-solid-wood-table.jpg" && echo "ok  ec-solid-wood-table.jpg" || echo "FAIL ec-solid-wood-table.jpg"
curl -L -sS "https://unsplash.com/photos/KP7p0-DRGbg/download?force=true&w=2400" -o "ec-pendant.jpg" && echo "ok  ec-pendant.jpg" || echo "FAIL ec-pendant.jpg"
curl -L -sS "https://unsplash.com/photos/wby4nFO-m8o/download?force=true&w=2400" -o "lookbook-04-detail-b.jpg" && echo "ok  lookbook-04-detail-b.jpg" || echo "FAIL lookbook-04-detail-b.jpg"
curl -L -sS "https://unsplash.com/photos/-_GU-VDIHnk/download?force=true&w=2400" -o "lookbook-03-wide.jpg" && echo "ok  lookbook-03-wide.jpg" || echo "FAIL lookbook-03-wide.jpg"
curl -L -sS "https://unsplash.com/photos/kUd6KkVfbCY/download?force=true&w=2400" -o "lookbook-03-detail-a.jpg" && echo "ok  lookbook-03-detail-a.jpg" || echo "FAIL lookbook-03-detail-a.jpg"
curl -L -sS "https://unsplash.com/photos/EKe_cbaqJ2A/download?force=true&w=2400" -o "lookbook-03-detail-b.jpg" && echo "ok  lookbook-03-detail-b.jpg" || echo "FAIL lookbook-03-detail-b.jpg"
curl -L -sS "https://unsplash.com/photos/iSO22I2l5uc/download?force=true&w=2400" -o "ec-kids-bed.jpg" && echo "ok  ec-kids-bed.jpg" || echo "FAIL ec-kids-bed.jpg"
curl -L -sS "https://unsplash.com/photos/B2vrSzxm43U/download?force=true&w=2400" -o "ec-wool-rug.jpg" && echo "ok  ec-wool-rug.jpg" || echo "FAIL ec-wool-rug.jpg"
curl -L -sS "https://unsplash.com/photos/uNZpPRPEnY4/download?force=true&w=2400" -o "ec-compact-sofa.jpg" && echo "ok  ec-compact-sofa.jpg" || echo "FAIL ec-compact-sofa.jpg"
curl -L -sS "https://unsplash.com/photos/faJf1aDiezQ/download?force=true&w=2400" -o "ec-floor-lamp.jpg" && echo "ok  ec-floor-lamp.jpg" || echo "FAIL ec-floor-lamp.jpg"
curl -L -sS "https://unsplash.com/photos/H_eb_VfG2Ow/download?force=true&w=2400" -o "lookbook-01-detail-a.jpg" && echo "ok  lookbook-01-detail-a.jpg" || echo "FAIL lookbook-01-detail-a.jpg"
curl -L -sS "https://unsplash.com/photos/mGI8b4KFoFM/download?force=true&w=2400" -o "home-detail.jpg" && echo "ok  home-detail.jpg" || echo "FAIL home-detail.jpg"
curl -L -sS "https://unsplash.com/photos/TWOnvtstmeU/download?force=true&w=2400" -o "lookbook-02-detail-b.jpg" && echo "ok  lookbook-02-detail-b.jpg" || echo "FAIL lookbook-02-detail-b.jpg"
curl -L -sS "https://unsplash.com/photos/8mNGNld9cBA/download?force=true&w=2400" -o "lookbook-02-detail-a.jpg" && echo "ok  lookbook-02-detail-a.jpg" || echo "FAIL lookbook-02-detail-a.jpg"
curl -L -sS "https://unsplash.com/photos/DGRixfygKvE/download?force=true&w=2400" -o "contact-studio.jpg" && echo "ok  contact-studio.jpg" || echo "FAIL contact-studio.jpg"
curl -L -sS "https://unsplash.com/photos/pdCTX1harH4/download?force=true&w=2400" -o "about-scale.jpg" && echo "ok  about-scale.jpg" || echo "FAIL about-scale.jpg"
curl -L -sS "https://unsplash.com/photos/U-Dhokv9iXk/download?force=true&w=2400" -o "about-location.jpg" && echo "ok  about-location.jpg" || echo "FAIL about-location.jpg"
curl -L -sS "https://unsplash.com/photos/JSUUbTs_UZ0/download?force=true&w=2400" -o "lookbook-04-detail-a.jpg" && echo "ok  lookbook-04-detail-a.jpg" || echo "FAIL lookbook-04-detail-a.jpg"
curl -L -sS "https://unsplash.com/photos/_uOCL2SJMy4/download?force=true&w=2400" -o "journal-sofa-depth.jpg" && echo "ok  journal-sofa-depth.jpg" || echo "FAIL journal-sofa-depth.jpg"
curl -L -sS "https://unsplash.com/photos/whoL0IGd5Ec/download?force=true&w=2400" -o "home-outdoor.jpg" && echo "ok  home-outdoor.jpg" || echo "FAIL home-outdoor.jpg"
curl -L -sS "https://unsplash.com/photos/CrMr84Mb9Y4/download?force=true&w=2400" -o "lookbook-05-wide.jpg" && echo "ok  lookbook-05-wide.jpg" || echo "FAIL lookbook-05-wide.jpg"
curl -L -sS "https://unsplash.com/photos/EE6_axVwfnM/download?force=true&w=2400" -o "lookbook-05-detail-a.jpg" && echo "ok  lookbook-05-detail-a.jpg" || echo "FAIL lookbook-05-detail-a.jpg"
curl -L -sS "https://unsplash.com/photos/FPQIl8rU7Kk/download?force=true&w=2400" -o "lookbook-05-detail-b.jpg" && echo "ok  lookbook-05-detail-b.jpg" || echo "FAIL lookbook-05-detail-b.jpg"
curl -L -sS "https://unsplash.com/photos/IA_qTLJK7ig/download?force=true&w=2400" -o "ec-outdoor-sofa.jpg" && echo "ok  ec-outdoor-sofa.jpg" || echo "FAIL ec-outdoor-sofa.jpg"
curl -L -sS "https://unsplash.com/photos/ARLPIlSHvXc/download?force=true&w=2400" -o "ec-outdoor-dining.jpg" && echo "ok  ec-outdoor-dining.jpg" || echo "FAIL ec-outdoor-dining.jpg"
echo "done"
